export const LANGUAGES = [
  { label: 'Acholi (Uganda)', value: 'Acholi' },
  { label: 'Afar (Djibouti/Ethiopia)', value: 'Afar' },
  { label: 'Afrikaans (South Africa)', value: 'Afrikaans' },
  { label: 'Akan / Fante (Ghana)', value: 'Akan' },
  { label: 'Amharic (Ethiopia)', value: 'Amharic' },
  { label: 'Arabic', value: 'Arabic' },
  { label: 'Bambara (Mali)', value: 'Bambara' },
  { label: 'Baoulé (Côte d\'Ivoire)', value: 'Baoule' },
  { label: 'Bassa (Liberia)', value: 'Bassa' },
  { label: 'Bemba (Zambia)', value: 'Bemba' },
  { label: 'Bengali', value: 'Bengali' },
  { label: 'Berber / Tamazight (North Africa)', value: 'Tamazight' },
  { label: 'Bété (Côte d\'Ivoire)', value: 'Bete' },
  { label: 'Cape Verdean Creole (Kabuverdianu)', value: 'Cape Verdean Creole' },
  { label: 'Chichewa / Nyanja (Malawi/Zambia)', value: 'Chichewa' },
  { label: 'Chinese (Mandarin)', value: 'Chinese' },
  { label: 'Chokwe (Angola/DRC)', value: 'Chokwe' },
  { label: 'Comorian / Shikomor (Comoros)', value: 'Comorian' },
  { label: 'Dagaare (Ghana/Burkina Faso)', value: 'Dagaare' },
  { label: 'Dagbani (Ghana)', value: 'Dagbani' },
  { label: 'Dinka (South Sudan)', value: 'Dinka' },
  { label: 'Dutch', value: 'Dutch' },
  { label: 'Dyula / Jula (West Africa)', value: 'Dyula' },
  { label: 'Edo / Bini (Nigeria)', value: 'Edo' },
  { label: 'Efik / Ibibio (Nigeria)', value: 'Efik' },
  { label: 'English', value: 'English' },
  { label: 'Ewe (Togo/Ghana)', value: 'Ewe' },
  { label: 'Fang (Gabon/Eq. Guinea)', value: 'Fang' },
  { label: 'Fon (Benin)', value: 'Fon' },
  { label: 'French', value: 'French' },
  { label: 'Fula / Fulani / Fulfulde (West Africa)', value: 'Fulani' },
  { label: 'Ga (Ghana)', value: 'Ga' },
  { label: 'Gbaya (Central African Republic)', value: 'Gbaya' },
  { label: 'German', value: 'German' },
  { label: 'Gikuyu / Kikuyu (Kenya)', value: 'Kikuyu' },
  { label: 'Harari (Ethiopia)', value: 'Harari' },
  { label: 'Hausa (Nigeria/Niger)', value: 'Hausa' },
  { label: 'Herero (Namibia)', value: 'Herero' },
  { label: 'Hindi', value: 'Hindi' },
  { label: 'Ibibio (Nigeria)', value: 'Ibibio' },
  { label: 'Idoma (Nigeria)', value: 'Idoma' },
  { label: 'Igala (Nigeria)', value: 'Igala' },
  { label: 'Igbo (Nigeria)', value: 'Igbo' },
  { label: 'Ijaw (Nigeria)', value: 'Ijaw' },
  { label: 'Indonesian', value: 'Indonesian' },
  { label: 'Isoko (Nigeria)', value: 'Isoko' },
  { label: 'Italian', value: 'Italian' },
  { label: 'Itsekiri (Nigeria)', value: 'Itsekiri' },
  { label: 'Japanese', value: 'Japanese' },
  { label: 'Kabyle (Algeria)', value: 'Kabyle' },
  { label: 'Kalenjin (Kenya)', value: 'Kalenjin' },
  { label: 'Kamba (Kenya)', value: 'Kamba' },
  { label: 'Kanuri (Nigeria/Chad)', value: 'Kanuri' },
  { label: 'Kikongo / Kongo (Congo/Angola)', value: 'Kikongo' },
  { label: 'Kimbundu (Angola)', value: 'Kimbundu' },
  { label: 'Kinyarwanda (Rwanda)', value: 'Kinyarwanda' },
  { label: 'Kirundi / Rundi (Burundi)', value: 'Kirundi' },
  { label: 'Kituba (Congo)', value: 'Kituba' },
  { label: 'Korean', value: 'Korean' },
  { label: 'Kpelle (Liberia/Guinea)', value: 'Kpelle' },
  { label: 'Krio (Sierra Leone)', value: 'Krio' },
  { label: 'Lingala (DR Congo/Congo)', value: 'Lingala' },
  { label: 'Luganda (Uganda)', value: 'Luganda' },
  { label: 'Luhya (Kenya)', value: 'Luhya' },
  { label: 'Luo / Dholuo (Kenya/Uganda)', value: 'Luo' },
  { label: 'Maasai (Kenya/Tanzania)', value: 'Maasai' },
  { label: 'Malagasy (Madagascar)', value: 'Malagasy' },
  { label: 'Mambwe-Lungu (Zambia)', value: 'Mambwe' },
  { label: 'Mandinka (Gambia/Senegal)', value: 'Mandinka' },
  { label: 'Mauritian Creole (Mauritius)', value: 'Mauritian Creole' },
  { label: 'Mende (Sierra Leone)', value: 'Mende' },
  { label: 'Mongo (DR Congo)', value: 'Mongo' },
  { label: 'Mooré / Mossi (Burkina Faso)', value: 'Moore' },
  { label: 'Nama / Khoekhoe (Namibia)', value: 'Nama' },
  { label: 'Ndebele (Zimbabwe/South Africa)', value: 'Ndebele' },
  { label: 'Nuer (South Sudan)', value: 'Nuer' },
  { label: 'Nupe (Nigeria)', value: 'Nupe' },
  { label: 'Nyankore / Runyankore (Uganda)', value: 'Runyankore' },
  { label: 'Oromo (Ethiopia/Kenya)', value: 'Oromo' },
  { label: 'Oshiwambo / Ndonga (Namibia)', value: 'Oshiwambo' },
  { label: 'Polish', value: 'Polish' },
  { label: 'Portuguese', value: 'Portuguese' },
  { label: 'Russian', value: 'Russian' },
  { label: 'Sango (Central African Republic)', value: 'Sango' },
  { label: 'Sena (Mozambique)', value: 'Sena' },
  { label: 'Sepedi / Northern Sotho (South Africa)', value: 'Sepedi' },
  { label: 'Serer (Senegal)', value: 'Serer' },
  { label: 'Sesotho (Lesotho/South Africa)', value: 'Sesotho' },
  { label: 'Setswana / Tswana (Botswana/South Africa)', value: 'Setswana' },
  { label: 'Seychellois Creole (Seychelles)', value: 'Seychellois Creole' },
  { label: 'Shona (Zimbabwe)', value: 'Shona' },
  { label: 'Sidama (Ethiopia)', value: 'Sidama' },
  { label: 'siSwati / Swati (Eswatini/South Africa)', value: 'Swati' },
  { label: 'Somali (Somalia/Djibouti)', value: 'Somali' },
  { label: 'Songhai (Mali/Niger)', value: 'Songhai' },
  { label: 'Soninke (Mali/Senegal)', value: 'Soninke' },
  { label: 'Spanish', value: 'Spanish' },
  { label: 'Sukuma (Tanzania)', value: 'Sukuma' },
  { label: 'Susu (Guinea/Sierra Leone)', value: 'Susu' },
  { label: 'Swahili (East Africa)', value: 'Swahili' },
  { label: 'Tamil', value: 'Tamil' },
  { label: 'Temne (Sierra Leone)', value: 'Temne' },
  { label: 'Thai', value: 'Thai' },
  { label: 'Tigrinya (Eritrea/Ethiopia)', value: 'Tigrinya' },
  { label: 'Tiv (Nigeria)', value: 'Tiv' },
  { label: 'Tonga (Zambia/Zimbabwe)', value: 'Tonga' },
  { label: 'Tshiluba / Luba-Kasai (DR Congo)', value: 'Tshiluba' },
  { label: 'Tshivenda / Venda (South Africa)', value: 'Tshivenda' },
  { label: 'Tsonga / Xitsonga (South Africa)', value: 'Tsonga' },
  { label: 'Tumbuka (Malawi/Zambia)', value: 'Tumbuka' },
  { label: 'Turkish', value: 'Turkish' },
  { label: 'Twi (Ghana)', value: 'Twi' },
  { label: 'Umbundu (Angola)', value: 'Umbundu' },
  { label: 'Urdu', value: 'Urdu' },
  { label: 'Urhobo (Nigeria)', value: 'Urhobo' },
  { label: 'Vietnamese', value: 'Vietnamese' },
  { label: 'Wolof (Senegal/Gambia)', value: 'Wolof' },
  { label: 'Xhosa (South Africa)', value: 'Xhosa' },
  { label: 'Yoruba (Nigeria)', value: 'Yoruba' },
  { label: 'Zarma (Niger)', value: 'Zarma' },
  { label: 'Zulu (South Africa)', value: 'Zulu' },
] as const;

export type LanguageValue = typeof LANGUAGES[number]['value'];

export interface LanguageInfo {
  name: string;
  code: string; // BCP-47 / ISO
  flag: string; // Emoji flag
  speechCode: string; // e.g. en-US, fr-FR, sw-KE
  rtl?: boolean;
}

export const LANGUAGE_METADATA: Record<string, LanguageInfo> = {
  Acholi: { name: 'Acholi', code: 'ach', flag: '🇺🇬', speechCode: 'ach-UG' },
  Afar: { name: 'Afar', code: 'aa', flag: '🇩🇯', speechCode: 'aa-DJ' },
  Afrikaans: { name: 'Afrikaans', code: 'af', flag: '🇿🇦', speechCode: 'af-ZA' },
  Akan: { name: 'Akan', code: 'ak', flag: '🇬🇭', speechCode: 'ak-GH' },
  Amharic: { name: 'Amharic', code: 'am', flag: '🇪🇹', speechCode: 'am-ET' },
  Arabic: { name: 'Arabic', code: 'ar', flag: '🇸🇦', speechCode: 'ar-SA', rtl: true },
  Bambara: { name: 'Bambara', code: 'bm', flag: '🇲🇱', speechCode: 'bm-ML' },
  Baoule: { name: 'Baoulé', code: 'bci', flag: '🇨🇮', speechCode: 'bci-CI' },
  Bassa: { name: 'Bassa', code: 'bsq', flag: '🇱🇷', speechCode: 'bsq-LR' },
  Bemba: { name: 'Bemba', code: 'bem', flag: '🇿🇲', speechCode: 'bem-ZM' },
  Bengali: { name: 'Bengali', code: 'bn', flag: '🇧🇩', speechCode: 'bn-BD' },
  Bete: { name: 'Bété', code: 'btg', flag: '🇨🇮', speechCode: 'btg-CI' },
  CapeVerdeanCreole: { name: 'Cape Verdean Creole', code: 'kea', flag: '🇨🇻', speechCode: 'kea-CV' },
  'Cape Verdean Creole': { name: 'Cape Verdean Creole', code: 'kea', flag: '🇨🇻', speechCode: 'kea-CV' },
  Chichewa: { name: 'Chichewa', code: 'ny', flag: '🇲🇼', speechCode: 'ny-MW' },
  Chinese: { name: 'Chinese', code: 'zh', flag: '🇨🇳', speechCode: 'zh-CN' },
  Chokwe: { name: 'Chokwe', code: 'cjk', flag: '🇦🇴', speechCode: 'cjk-AO' },
  Comorian: { name: 'Comorian', code: 'swb', flag: '🇰🇲', speechCode: 'swb-KM' },
  Dagaare: { name: 'Dagaare', code: 'dga', flag: '🇬🇭', speechCode: 'dga-GH' },
  Dagbani: { name: 'Dagbani', code: 'dag', flag: '🇬🇭', speechCode: 'dag-GH' },
  Dinka: { name: 'Dinka', code: 'din', flag: '🇸🇸', speechCode: 'din-SS' },
  Dutch: { name: 'Dutch', code: 'nl', flag: '🇳🇱', speechCode: 'nl-NL' },
  Dyula: { name: 'Dyula', code: 'dyu', flag: '🇨🇮', speechCode: 'dyu-CI' },
  Edo: { name: 'Edo', code: 'bin', flag: '🇳🇬', speechCode: 'bin-NG' },
  Efik: { name: 'Efik', code: 'efi', flag: '🇳🇬', speechCode: 'efi-NG' },
  English: { name: 'English', code: 'en', flag: '🇺🇸', speechCode: 'en-US' },
  Ewe: { name: 'Ewe', code: 'ee', flag: '🇹🇬', speechCode: 'ee-TG' },
  Fang: { name: 'Fang', code: 'fan', flag: '🇬🇶', speechCode: 'fan-GQ' },
  Fon: { name: 'Fon', code: 'fon', flag: '🇧🇯', speechCode: 'fon-BJ' },
  French: { name: 'French', code: 'fr', flag: '🇫🇷', speechCode: 'fr-FR' },
  Fulani: { name: 'Fulani', code: 'ff', flag: '🇸🇳', speechCode: 'ff-SN' },
  Ga: { name: 'Ga', code: 'gaa', flag: '🇬🇭', speechCode: 'gaa-GH' },
  Gbaya: { name: 'Gbaya', code: 'gba', flag: '🇨🇫', speechCode: 'gba-CF' },
  German: { name: 'German', code: 'de', flag: '🇩🇪', speechCode: 'de-DE' },
  Harari: { name: 'Harari', code: 'har', flag: '🇪🇹', speechCode: 'har-ET' },
  Hausa: { name: 'Hausa', code: 'ha', flag: '🇳🇬', speechCode: 'ha-NG' },
  Herero: { name: 'Herero', code: 'hz', flag: '🇳🇦', speechCode: 'hz-NA' },
  Hindi: { name: 'Hindi', code: 'hi', flag: '🇮🇳', speechCode: 'hi-IN' },
  Ibibio: { name: 'Ibibio', code: 'ibb', flag: '🇳🇬', speechCode: 'ibb-NG' },
  Idoma: { name: 'Idoma', code: 'idu', flag: '🇳🇬', speechCode: 'idu-NG' },
  Igala: { name: 'Igala', code: 'igl', flag: '🇳🇬', speechCode: 'igl-NG' },
  Igbo: { name: 'Igbo', code: 'ig', flag: '🇳🇬', speechCode: 'ig-NG' },
  Ijaw: { name: 'Ijaw', code: 'ijc', flag: '🇳🇬', speechCode: 'ijc-NG' },
  Indonesian: { name: 'Indonesian', code: 'id', flag: '🇮🇩', speechCode: 'id-ID' },
  Isoko: { name: 'Isoko', code: 'iso', flag: '🇳🇬', speechCode: 'iso-NG' },
  Italian: { name: 'Italian', code: 'it', flag: '🇮🇹', speechCode: 'it-IT' },
  Itsekiri: { name: 'Itsekiri', code: 'its', flag: '🇳🇬', speechCode: 'its-NG' },
  Japanese: { name: 'Japanese', code: 'ja', flag: '🇯🇵', speechCode: 'ja-JP' },
  Kabyle: { name: 'Kabyle', code: 'kab', flag: '🇩🇿', speechCode: 'kab-DZ' },
  Kalenjin: { name: 'Kalenjin', code: 'kln', flag: '🇰🇪', speechCode: 'kln-KE' },
  Kamba: { name: 'Kamba', code: 'kam', flag: '🇰🇪', speechCode: 'kam-KE' },
  Kanuri: { name: 'Kanuri', code: 'kr', flag: '🇳🇬', speechCode: 'kr-NG' },
  Kikongo: { name: 'Kikongo', code: 'kg', flag: '🇨🇩', speechCode: 'kg-CD' },
  Kikuyu: { name: 'Kikuyu', code: 'ki', flag: '🇰🇪', speechCode: 'ki-KE' },
  Kimbundu: { name: 'Kimbundu', code: 'kmb', flag: '🇦🇴', speechCode: 'kmb-AO' },
  Kinyarwanda: { name: 'Kinyarwanda', code: 'rw', flag: '🇷🇼', speechCode: 'rw-RW' },
  Kirundi: { name: 'Kirundi', code: 'rn', flag: '🇧🇮', speechCode: 'rn-BI' },
  Kituba: { name: 'Kituba', code: 'ktu', flag: '🇨🇬', speechCode: 'ktu-CG' },
  Korean: { name: 'Korean', code: 'ko', flag: '🇰🇷', speechCode: 'ko-KR' },
  Kpelle: { name: 'Kpelle', code: 'kpe', flag: '🇱🇷', speechCode: 'kpe-LR' },
  Krio: { name: 'Krio', code: 'kri', flag: '🇸🇱', speechCode: 'kri-SL' },
  Lingala: { name: 'Lingala', code: 'ln', flag: '🇨🇩', speechCode: 'ln-CD' },
  Luganda: { name: 'Luganda', code: 'lg', flag: '🇺🇬', speechCode: 'lg-UG' },
  Luhya: { name: 'Luhya', code: 'luy', flag: '🇰🇪', speechCode: 'luy-KE' },
  Luo: { name: 'Luo', code: 'luo', flag: '🇰🇪', speechCode: 'luo-KE' },
  Maasai: { name: 'Maasai', code: 'mas', flag: '🇰🇪', speechCode: 'mas-KE' },
  Malagasy: { name: 'Malagasy', code: 'mg', flag: '🇲🇬', speechCode: 'mg-MG' },
  Mambwe: { name: 'Mambwe', code: 'mgr', flag: '🇿🇲', speechCode: 'mgr-ZM' },
  Mandinka: { name: 'Mandinka', code: 'mnk', flag: '🇬🇲', speechCode: 'mnk-GM' },
  MauritianCreole: { name: 'Mauritian Creole', code: 'mfe', flag: '🇲🇺', speechCode: 'mfe-MU' },
  'Mauritian Creole': { name: 'Mauritian Creole', code: 'mfe', flag: '🇲🇺', speechCode: 'mfe-MU' },
  Mende: { name: 'Mende', code: 'men', flag: '🇸🇱', speechCode: 'men-SL' },
  Mongo: { name: 'Mongo', code: 'lol', flag: '🇨🇩', speechCode: 'lol-CD' },
  Moore: { name: 'Mooré', code: 'mos', flag: '🇧🇫', speechCode: 'mos-BF' },
  Nama: { name: 'Nama', code: 'naq', flag: '🇳🇦', speechCode: 'naq-NA' },
  Ndebele: { name: 'Ndebele', code: 'nd', flag: '🇿🇼', speechCode: 'nd-ZW' },
  Nuer: { name: 'Nuer', code: 'nus', flag: '🇸🇸', speechCode: 'nus-SS' },
  Nupe: { name: 'Nupe', code: 'nup', flag: '🇳🇬', speechCode: 'nup-NG' },
  Oromo: { name: 'Oromo', code: 'om', flag: '🇪🇹', speechCode: 'om-ET' },
  Oshiwambo: { name: 'Oshiwambo', code: 'ng', flag: '🇳🇦', speechCode: 'ng-NA' },
  Polish: { name: 'Polish', code: 'pl', flag: '🇵🇱', speechCode: 'pl-PL' },
  Portuguese: { name: 'Portuguese', code: 'pt', flag: '🇵🇹', speechCode: 'pt-PT' },
  Runyankore: { name: 'Runyankore', code: 'nyn', flag: '🇺🇬', speechCode: 'nyn-UG' },
  Russian: { name: 'Russian', code: 'ru', flag: '🇷🇺', speechCode: 'ru-RU' },
  Sango: { name: 'Sango', code: 'sg', flag: '🇨🇫', speechCode: 'sg-CF' },
  Sena: { name: 'Sena', code: 'seh', flag: '🇲🇿', speechCode: 'seh-MZ' },
  Sepedi: { name: 'Sepedi', code: 'nso', flag: '🇿🇦', speechCode: 'nso-ZA' },
  Serer: { name: 'Serer', code: 'srr', flag: '🇸🇳', speechCode: 'srr-SN' },
  Sesotho: { name: 'Sesotho', code: 'st', flag: '🇱🇸', speechCode: 'st-ZA' },
  Setswana: { name: 'Setswana', code: 'tn', flag: '🇧🇼', speechCode: 'tn-BW' },
  SeychelloisCreole: { name: 'Seychellois Creole', code: 'crs', flag: '🇸🇨', speechCode: 'crs-SC' },
  'Seychellois Creole': { name: 'Seychellois Creole', code: 'crs', flag: '🇸🇨', speechCode: 'crs-SC' },
  Shona: { name: 'Shona', code: 'sn', flag: '🇿🇼', speechCode: 'sn-ZW' },
  Sidama: { name: 'Sidama', code: 'sid', flag: '🇪🇹', speechCode: 'sid-ET' },
  Somali: { name: 'Somali', code: 'so', flag: '🇸🇴', speechCode: 'so-SO' },
  Songhai: { name: 'Songhai', code: 'son', flag: '🇲🇱', speechCode: 'son-ML' },
  Soninke: { name: 'Soninke', code: 'snk', flag: '🇲🇱', speechCode: 'snk-ML' },
  Spanish: { name: 'Spanish', code: 'es', flag: '🇪🇸', speechCode: 'es-ES' },
  Sukuma: { name: 'Sukuma', code: 'suk', flag: '🇹🇿', speechCode: 'suk-TZ' },
  Susu: { name: 'Susu', code: 'sus', flag: '🇬🇳', speechCode: 'sus-GN' },
  Swahili: { name: 'Swahili', code: 'sw', flag: '🇰🇪', speechCode: 'sw-KE' },
  Swati: { name: 'siSwati', code: 'ss', flag: '🇸🇿', speechCode: 'ss-SZ' },
  Tamazight: { name: 'Tamazight', code: 'zgh', flag: '🇲🇦', speechCode: 'zgh-MA' },
  Tamil: { name: 'Tamil', code: 'ta', flag: '🇮🇳', speechCode: 'ta-IN' },
  Temne: { name: 'Temne', code: 'tem', flag: '🇸🇱', speechCode: 'tem-SL' },
  Thai: { name: 'Thai', code: 'th', flag: '🇹🇭', speechCode: 'th-TH' },
  Tigrinya: { name: 'Tigrinya', code: 'ti', flag: '🇪🇷', speechCode: 'ti-ER' },
  Tiv: { name: 'Tiv', code: 'tiv', flag: '🇳🇬', speechCode: 'tiv-NG' },
  Tonga: { name: 'Tonga', code: 'toi', flag: '🇿🇲', speechCode: 'toi-ZM' },
  Tshiluba: { name: 'Tshiluba', code: 'lua', flag: '🇨🇩', speechCode: 'lua-CD' },
  Tshivenda: { name: 'Tshivenda', code: 've', flag: '🇿🇦', speechCode: 've-ZA' },
  Tsonga: { name: 'Xitsonga', code: 'ts', flag: '🇿🇦', speechCode: 'ts-ZA' },
  Tumbuka: { name: 'Tumbuka', code: 'tum', flag: '🇲🇼', speechCode: 'tum-MW' },
  Turkish: { name: 'Turkish', code: 'tr', flag: '🇹🇷', speechCode: 'tr-TR' },
  Twi: { name: 'Twi', code: 'ak', flag: '🇬🇭', speechCode: 'ak-GH' },
  Umbundu: { name: 'Umbundu', code: 'umb', flag: '🇦🇴', speechCode: 'umb-AO' },
  Urdu: { name: 'Urdu', code: 'ur', flag: '🇵🇰', speechCode: 'ur-PK', rtl: true },
  Urhobo: { name: 'Urhobo', code: 'urh', flag: '🇳🇬', speechCode: 'urh-NG' },
  Vietnamese: { name: 'Vietnamese', code: 'vi', flag: '🇻🇳', speechCode: 'vi-VN' },
  Wolof: { name: 'Wolof', code: 'wo', flag: '🇸🇳', speechCode: 'wo-SN' },
  Xhosa: { name: 'Xhosa', code: 'xh', flag: '🇿🇦', speechCode: 'xh-ZA' },
  Yoruba: { name: 'Yoruba', code: 'yo', flag: '🇳🇬', speechCode: 'yo-NG' },
  Zarma: { name: 'Zarma', code: 'dje', flag: '🇳🇪', speechCode: 'dje-NE' },
  Zulu: { name: 'Zulu', code: 'zu', flag: '🇿🇦', speechCode: 'zu-ZA' },
};

export const POPULAR_LANGUAGES: string[] = [
  'English',
  'Kinyarwanda',
  'Spanish',
  'French',
  'Swahili',
  'Yoruba',
  'Hausa',
  'Amharic',
  'Zulu',
  'Igbo',
  'Arabic',
  'German',
  'Portuguese',
  'Chinese',
];

export function getLanguageMetadata(name?: string | null): LanguageInfo {
  if (!name) return { name: 'English', code: 'en', flag: '🇺🇸', speechCode: 'en-US' };
  return (
    LANGUAGE_METADATA[name] || {
      name,
      code: 'en',
      flag: '🌐',
      speechCode: 'en-US',
    }
  );
}

export const EARLY_ADOPTER_LIMIT = 5000;
export const EARLY_ADOPTER_PLAN = 'early_adopter_pioneer';
export const STANDARD_PLAN = 'standard';

export const USERNAME_REGEX = /^[a-zA-Z0-9_]{3,30}$/;
export const MAX_MESSAGE_LENGTH = 5000;
